apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: docker-test-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/popcor255/nocode
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: docker-build
      taskRef:
        name: docker-build
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image
          value: registry.default.svc.cluster.local:5000/nocode
        - name: insecure_registry
          value: registry.default.svc.cluster.local:5000
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: docker-test-pipeline-run
spec:
  pipelineRef:
    name: docker-test-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: docker-source-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-docker-build-local
  namespace: default
spec:
  selector:
    matchLabels:
      app: registry-docker-build-local
  template:
    metadata:
      labels:
        app: registry-docker-build-local
    spec:
      containers:
        - name: registry-docker-build-local
          image: hyperledgerk8s/registry:2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
spec:
  selector:
    app: registry-docker-build-local
  ports:
    - port: 5000
      targetPort: 5000
