apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blockchain:common
rules:
- apiGroups:
    - ibp.com
  resources:
    - organizations
  verbs:
    - create
    - get
    - list
- apiGroups:
    - ibp.com
  resources:
    - federations
    - proposals
    - networks
    - channels
  verbs:
    - create
