---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-pod
spec:
  backoffLimit: 4
  template:
    spec:
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: kaniko-tar-source-pvc
      containers:
      - name: downloader
        image: busybox
        command: ["/bin/sh", "-c"]
        # https://github.com/olliefr/docker-gs-ping is example project for Docker's "Getting Started with Docker and Go".
        args: ["wget -qO- https://github.com/olliefr/docker-gs-ping/archive/refs/tags/v0.0.4.zip > /mnt/go-src.zip"]
        volumeMounts:
        - name: pvc
          mountPath: /mnt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-tar-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-kaniko-tar-file
  namespace: default
spec:
  selector:
    matchLabels:
      app: registry-kaniko-tar-file
  template:
    metadata:
      labels:
        app: registry-kaniko-tar-file
    spec:
      containers:
        - name: registry-kaniko-tar-file
          image: hyperledgerk8s/registry:2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry-kaniko-tar-file
  namespace: default
spec:
  selector:
    app: registry-kaniko-tar-file
  ports:
    - port: 5000
      targetPort: 5000
