apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.bcapi.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 8024
    protocol: TCP
    targetPort: 8024
  selector:
    app: bc-apis
  sessionAffinity: None
  type: ClusterIP