---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-test-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: image
      description: reference of the image to build
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/kelseyhightower/nocode
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: kaniko
      taskRef:
        name: kaniko
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image)
        - name: EXTRA_ARGS
          value:
            - --skip-tls-verify
    - name: verify-digest
      runAfter:
        - kaniko
      params:
        - name: digest
          value: $(tasks.kaniko.results.IMAGE_DIGEST)
      taskSpec:
        params:
          - name: digest
        steps:
          - name: bash
            image: hyperledgerk8s/ubuntu:22.04
            script: |
              echo $(params.digest)
              case .$(params.digest) in
                ".sha"*) exit 0 ;;
                *)       echo "Digest value is not correct" && exit 1 ;;
              esac
    - name: verify-url
      runAfter:
        - kaniko
      params:
        - name: url
          value: $(tasks.kaniko.results.IMAGE_URL)
      taskSpec:
        params:
          - name: url
        steps:
          - name: bash
            image: hyperledgerk8s/ubuntu:22.04
            script: |
              echo $(params.url)
              case .$(params.url) in
                *"/kaniko-nocode") exit 0 ;;
                *)       echo "URL value is not correct" && exit 1 ;;
              esac
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: kaniko-test-pipeline-run
spec:
  pipelineRef:
    name: kaniko-test-pipeline
  params:
    - name: image
      value: registry.default.svc.cluster.local:5000/kaniko-nocode
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: kaniko-source-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-docker-build-local
  namespace: default
spec:
  selector:
    matchLabels:
      app: registry-docker-build-local
  template:
    metadata:
      labels:
        app: registry-docker-build-local
    spec:
      containers:
        - name: registry-docker-build-local
          image: hyperledgerk8s/registry:2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
spec:
  selector:
    app: registry-docker-build-local
  ports:
    - port: 5000
      targetPort: 5000
