# You should run pre_sample_minio.yaml to store data to minio
# And run post_sample_minio.yaml to delete data from minio.
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-minio
  labels:
    description: "A_PipelineRun_For_ChaincodeBuild"
spec:
  pipelineRef:
    name: chaincodebuild
  params:
    - name: SOURCE
      value: minio
    - name: SOURCE_MINIO_BUCKET
      value: bestchains
    - name: SOURCE_MINIO_OBJECT
      value: go-contract
    - name: SOURCE_MINIO_HOST
      value: fabric-minio.baas-system.svc.cluster.local:9000
    - name: SOURCE_MINIO_ACCESS_KEY
      value: "q18aRFqWOAX7pEin"
    - name: SOURCE_MINIO_SECRET_KEY
      value: "nCbZIP6q4s8KtQpL7n8CD2N88H6XABGf"
    - name: APP_IMAGE
      value: registry-sample-minio.default.svc.cluster.local:5000/go-contract:latest
    - name: INSECURE_REGISTRY
      value: registry-sample-minio.default.svc.cluster.local:5000
    - name: DOCKERFILE
      value: bestchains/go-contract/samples/go-contract/Dockerfile.optimized # Only complete absolute paths  {bucket}/{object}/{optional-project-internal-path}
    - name: CONTEXT
      value: bestchains/go-contract/samples/go-contract/ # Must be in format {bucket}/{object}/{optional-project-internal-path}
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: sample-minio-ws-pvc
    - name: dockerconfig-ws
      secret:
        secretName: dockerhub-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-sample-minio
  namespace: default
spec:
  selector:
    matchLabels:
      app: registry-sample-minio
  template:
    metadata:
      labels:
        app: registry-sample-minio
    spec:
      containers:
        - name: registry-sample-minio
          image: hyperledgerk8s/registry:2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry-sample-minio
  namespace: default
spec:
  selector:
    app: registry-sample-minio
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-minio-ws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
