---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-image-ws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-minio-kaniko-chaincodebuild-pipelinerun
  labels:
    description: "A_PipelineRun_For_ChaincodeBuild"
spec:
  serviceAccountName: chaincodebuild-service-account
  pipelineRef:
    name: chaincodebuild-kaniko
  params:
    - name: SOURCE
      value: minio
    - name: SOURCE_MINIO_BUCKET
      value: bestchains
    - name: SOURCE_MINIO_OBJECT
      value: go-contract
    - name: SOURCE_MINIO_HOST
      value: minio.tekton-pipelines-addons.svc.cluster.local
    - name: SOURCE_MINIO_ACCESS_KEY
      value: "q18aRFqWOAX7pEin"
    - name: SOURCE_MINIO_SECRET_KEY
      value: "nCbZIP6q4s8KtQpL7n8CD2N88H6XABGf"
    - name: APP_IMAGE
      value: bjwswang/go-contract:latest
    - name: DOCKERFILE
      value: bestchains/go-contract/Dockerfile.optimized # Must be in format : {bucket}/{object}/{relevant_path_to_object_root_directory}
    - name: CONTEXT
      value: bestchains/go-contract # Must be in format {bucket}/{object}
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: cache-image-ws-pvc
