---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-git-kaniko-ws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-git-chaincodebuild-pipelinerun
  labels:
    description: "A_PipelineRun_For_ChaincodeBuild"
spec:
  serviceAccountName: chaincodebuild-service-account
  pipelineRef:
    name: chaincodebuild-kaniko
  params:
    - name: SOURCE
      value: git
    - name: SOURCE_GIT_URL
      value: https://github.com/bestchains/fabric-builder-k8s
    - name: APP_IMAGE
      value: hyperledgerk8s/go-contract:latest
    - name: DOCKERFILE
      value: bestchains/go-contract/Dockerfile.optimized # Must be in format : {bucket}/{object}/{relevant_path_to_object_root_directory}
    - name: CONTEXT
      value: bestchains/go-contract # Must be in format {bucket}/{object}
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: sample-git-kaniko-ws-pvc
    - name: dockerconfig-ws
      secret:
        secretName: dockerhub-secret
