# You should run pre_sample_minio.yaml to store data to minio
# And run post_sample_minio.yaml to delete data from minio.
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-minio-kaniko
  labels:
    description: "A_PipelineRun_For_ChaincodeBuild"
spec:
  pipelineRef:
    name: chaincodebuild-kaniko
  params:
    - name: SOURCE
      value: minio
    - name: SOURCE_MINIO_BUCKET
      value: bestchains
    - name: SOURCE_MINIO_OBJECT
      value: go-contract
    - name: SOURCE_MINIO_HOST
      value: fabric-minio.baas-system.svc.cluster.local:9000
    - name: SOURCE_MINIO_ACCESS_KEY
      value: "q18aRFqWOAX7pEin"
    - name: SOURCE_MINIO_SECRET_KEY
      value: "nCbZIP6q4s8KtQpL7n8CD2N88H6XABGf"
    - name: APP_IMAGE
      value: registry-sample-minio-kaniko.default.svc.cluster.local:5000/go-contract:latest
    - name: DOCKERFILE
      value: Dockerfile.optimized # Short paths in CONTEXT or complete absolute paths  {bucket}/{object}/{relevant_path_to_object_root_directory}
    - name: CONTEXT
      value: bestchains/go-contract/samples/go-contract/ # Must be in format {bucket}/{object}/{optional-project-internal-path}
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: sample-minio-kaniko-ws-pvc
    - name: dockerconfig-ws
      secret:
        secretName: dockerhub-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
data:
  # echo -n '{"auths":{"registry-sample-minio-kaniko.default.svc.cluster.local:5000":{"username":"testuser","password":"testpassword","auth":"dGVzdHVzZXI6dGVzdHBhc3N3b3Jk"}}}' | base64
  # auth的值是 echo -n "testuser:testpassword" | base64
  config.json: eyJhdXRocyI6eyJyZWdpc3RyeS1zYW1wbGUtbWluaW8ta2FuaWtvLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTAwMCI6eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwicGFzc3dvcmQiOiJ0ZXN0cGFzc3dvcmQiLCJhdXRoIjoiZEdWemRIVnpaWEk2ZEdWemRIQmhjM04zYjNKayJ9fX0=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-sample-minio-kaniko
  namespace: default
spec:
  selector:
    matchLabels:
      app: registry-sample-minio-kaniko
  template:
    metadata:
      labels:
        app: registry-sample-minio-kaniko
    spec:
      volumes:
        - name: auth
          projected:
            sources:
              - configMap:
                  name: simple-auth-file
      containers:
        - name: registry-sample-minio-kaniko
          image: hyperledgerk8s/registry:2
          env:
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry Realm
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /tmp/htpasswd
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: auth
              mountPath: /tmp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-auth-file
data:
  # docker run --entrypoint htpasswd httpd:2 -Bbn testuser testpassword > auth/htpasswd
  htpasswd: |-
    testuser:$2y$05$Gs64xV3b.VuEotFwvR416uZ.aFZihXdLobK5uge94wOrXKRiAtyra

---
apiVersion: v1
kind: Service
metadata:
  name: registry-sample-minio-kaniko
  namespace: default
spec:
  selector:
    app: registry-sample-minio-kaniko
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-minio-kaniko-ws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
