apiVersion: v1
kind: ServiceAccount
metadata:
  name: bc-saas
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bc-saas
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - persistentvolumeclaims
      - persistentvolumes
      - services
      - endpoints
      - events
      - configmaps
      - secrets
      - nodes
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
  - apiGroups:
      - ibp.com
    resources:
      - ibpcas.ibp.com
      - ibppeers.ibp.com
      - ibporderers.ibp.com
      - ibpconsoles.ibp.com
      - organizations.ibp.com
      - federations.ibp.com
      - networks.ibp.com
      - proposals.ibp.com
      - votes.ibp.com
      - channels.ibp.com
      - chaincodebuilds.ibp.com
      - ibpcas
      - ibppeers
      - ibporderers
      - ibpconsoles
      - organizations
      - federations
      - networks
      - proposals
      - votes
      - channels
      - chaincodebuilds
      - ibpcas/finalizers
      - ibppeers/finalizers
      - ibporderers/finalizers
      - ibpconsoles/finalizers
      - organizations/finalizers
      - federations/finalizers
      - networks/finalizers
      - proposals/finalizers
      - votes/finalizers
      - channels/finalizers
      - chaincodebuilds/finalizers
      - ibpcas/status
      - ibppeers/status
      - ibporderers/status
      - ibpconsoles/status
      - organizations/status
      - federations/status
      - networks/status
      - proposals/status
      - votes/status
      - channels/status
      - chaincodebuilds/status
      - chaincodes
      - chaincodes/status
      - endorsepolicies
      - endorsepolicies/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - iam.tenxcloud.com
    resources:
      - users.iam.tenxcloud.com
      - users
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bc-saas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bc-saas
subjects:
  - kind: ServiceAccount
    name: bc-saas
    namespace: {{ .Values.namespace }}